# Generated by Django 3.0.7 on 2020-06-20 19:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=4096)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField(max_length=4096)),
                ('link', models.URLField()),
                ('city', models.TextField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.CreateModel(
            name='UserToCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='group', to='tgbot.Category')),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='group', to='tgbot.User')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('text', models.TextField(blank=True, max_length=4096, null=True)),
                ('posted_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('city', models.TextField(blank=True, max_length=32, null=True)),
                ('metro', models.TextField(blank=True, max_length=128, null=True)),
                ('address', models.TextField(blank=True, max_length=4096, null=True)),
                ('category', models.TextField(blank=True, max_length=64, null=True)),
                ('is_book', models.BooleanField(default=False)),
                ('is_lost', models.BooleanField(default=False)),
                ('group_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='group', to='tgbot.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=4096)),
                ('post', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='group', to='tgbot.Post')),
            ],
        ),
    ]
