# Generated by Django 3.0.7 on 2020-06-20 09:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField(max_length=4096)),
                ('link', models.URLField()),
                ('city', models.TextField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('text', models.TextField(blank=True, max_length=4096, null=True)),
                ('posted_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('city', models.TextField(blank=True, max_length=32, null=True)),
                ('address', models.TextField(blank=True, max_length=4096, null=True)),
                ('group_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='group', to='tgbot.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=4096)),
                ('post', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='group', to='tgbot.Post')),
            ],
        ),
    ]
