# Generated by Django 3.0.7 on 2020-06-20 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0005_auto_20200620_1120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date',
            new_name='posted_date',
        ),
    ]
