# Generated by Django 3.0.7 on 2020-06-20 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0006_auto_20200620_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='posted_date',
        ),
    ]
