# Generated by Django 3.0.7 on 2020-06-20 08:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0007_remove_post_posted_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='posted_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
